-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- Create apartment_images table
-- CREATE TABLE apartment_images (
--     id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
--     apartment_id UUID NOT NULL REFERENCES apartments(id) ON DELETE CASCADE,
--     image_url TEXT NOT NULL,
--     uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
-- );
--
-- -- Create indexes
-- CREATE INDEX idx_apartment_images_apartment_id ON apartment_images(apartment_id);
